apiVersion: v1
kind: LimitRange
metadata:
  name: default-limits
spec:
  limits:
  - type: Container
    default:          # 如果 Pod 没写 limits，就用这个
      cpu: 1
      memory: 2Gi
    defaultRequest:
      cpu: 500m
      memory: 1Gi
    max:
      cpu: 2
      memory: 4Gi
