# policies/03-disallow-privileged.yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-privileged
spec:
  validationFailureAction: Enforce
  rules:
  - name: block-privileged
    match:
      any:
      - resources:
          kinds:
          - Pod
    validate:
      message: "Privileged containers are not allowed"
      deny:
        conditions:
        - key: "{{ request.object.spec.containers[*].securityContext.privileged || '' }}"
          operator: Equals
          value: true
